config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views
  root 'questions#index'

  resources :questions do
    resources :comments, only: [:create]
    resources :answers, only: [:create]
    post 'votes', to: 'votes#create', as: 'votes'
    delete 'votes', to: 'votes#destroy', as: 'votes_del'
  end

  post 'votes/:answer_id', to: 'votes#create', as: 'votes_answer'  
  delete 'votes/:answer_id', to: 'votes#destroy', as: 'votes_answer_del'

  post 'comments/:answer_id', to: 'comments#create', as: 'answer_comments'  

  devise_for :users
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :answers
  has_many :votes, as: :voteable
  #has_many :comments, as: :commentable

  validates :title, :presence => {:message => "no puede estar en blanco" }
  validates :body, :presence => {:message => "no puede estar en blanco" }

 
 
  def self.search(query)
    where("title like ?", "%#{query}%") 
  end  



end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
  	@questions = Question.all.order("created_at DESC")
    if params[:search]
      @questions = Question.search(params[:search]).order("created_at DESC")
    else
      @questions = Question.order("created_at DESC")
    end    
  end

  def new
  	@question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to questions_path, notice: "La Pregunta fue creada exitosamente."
    else
      render :new   
    end		
  end

  def show
    @question = Question.find(params[:id])    
    #Para el comentario, que pertenece a un post especifico.
    @comment = Comment.new
    @answer = Answer.new
    @vote = Vote.new
  end


  private 
    def question_params
      params.require(:question).permit(:title, :body)		
    end


end

app/helpers/questions_helper.rb
module QuestionsHelper
	def form_title
		@question.new_record? ? "Crear Pregunta" : "Editar Pregunta"		
	end		
end

app/views/questions/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-sm-offset-2">
			<h1><%= form_title %></h1>
			<% if @question.errors.any? %>
			  <div class="alert alert-danger">
			    <ul>
			    <% @question.errors.full_messages.each do |msg| %>
			      <li><%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			<% end %>			

			<%= form_for @question do |f| %>
				<div class="form-group">
					<%=  f.text_field :title, class: "form-control input-lg", placeholder: "Ingresa el titulo de la pregunta" %>
				</div>
				<div class="form-group">
					<%=  f.text_area :body, class: "form-control input-lg", placeholder: "Ingresa la descripción de la pregunta" %>
				</div>
				<div>
					<%= f.submit form_title, class: "btn btn-primary btn-lg" %> <%= link_to "Cancelar", questions_path, class: "btn btn-primary btn-lg" %>
				</div>	
			<% end %>
		</div> <!-- .col-sm -->
	</div> <!-- .row -->
</div> <!-- .container -->

app/views/questions/edit.html.erb
<%= render 'form' %>  

app/views/questions/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div id="questions">
	        	    <h1>Preguntas</h1>
	           </div>	
	        <div id="btn-questions">
				    <% if signed_in? %>
      	    		<%= link_to "Hacer una Pregunta", new_question_path, class: "btn btn-primary" %>
      	  		<% else %>
      	    		<%= link_to "Hacer una Pregunta", new_user_session_path, class: "btn btn-primary" %>
    	  		<% end %>	        	
      	  </div>
    </div>

    <table class="table table-responsive">
      <thead>
        <th class="col-sm-1"></th>
        <th class="col-sm-1"></th>
        <th class="col-sm-10"></th>
      </thead>
        <% @questions.each do |question| %>
          <tr>
            <td class="text-center"><h3><%= question.votes.count %></h3>Votos</td>
            <td class="text-center"><h3><%= question.answers.count %></h3>Respuestas</td>
            <td class="text-left">
              <div id="body-questions">
                <h4><%= link_to question.title, question %> </h4>
                <span>Preguntó <%= question.user.email %> hace alrededor de <%= time_ago_in_words question.created_at %> </span>
              </div>              
            </td>
            </div>
          </tr>
        <% end %>
      </table>
 
        </div> <!-- .col-->
    </div> <!-- .row-->
</div> <!-- .container -->

app/views/questions/new.html.erb
<%= render 'form' %>  

app/views/questions/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-8">
            <div id="question-title">
                <h1><%= @question.title %></h1>
            </div>	
            <div class="question-up">
                <% if signed_in? %>
                    <% if @question.votes.exists?(user_id: current_user.id) %>
                        <br>
                        <div id="vote-color">
                            <%= @question.votes.count %>
                        </div>                    
                        <%= link_to '<i class="fa fa-sort-desc fa-3x"></i>'.html_safe, question_votes_del_path(@question), method: :delete %> 
                    <% else %>
                        <br>
                        <div id="vote-color">
                            <%= @question.votes.count %>
                        </div>
                        <%= link_to '<i class="fa fa-sort-asc fa-3x"></i>'.html_safe, question_votes_path(@question), method: :post %> 
                    <% end %>
                <% end %>                
            </div>        

            <div class="question-up">
                <div id="question-content">
                    <strong><%= @question.body %></strong>                    
                </div>
            </div>            


            <% @question.comments.each do |question| %>
            	<hr>
            	<%= markdown(question.body) %>
            <% end %>
            <% if @comment %>
                <% if @comment.errors.any? %>
                  <div class="alert alert-danger">
                    <ul>
                    <% @comment.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                <% end %>
            <% end %>

            <% if signed_in? %>
                <%= form_for [@question,@question.comments.new] do |f| %>
                    <div class="form-group">
                        <%=  f.text_area :body, class: "form-control input-lg", placeholder: "Comentar Pregunta" %>
                    </div>
                    <div>
                        <%= f.submit "Comentar", class: "btn btn-primary" %>
                        <%= f.hidden_field :user_id, :value => current_user.id %>
                        <%= f.hidden_field :question_id, :value => @question.id %>
                    </div>  
                <% end %> 
            <% end %> 

            <h3><%= @question.answers.count %> Respuesta(s)</h3>
            <% @question.answers.each do |answer| %>
                <div id="vote-color">
                    <%= answer.votes.count %>
                </div>                    

                <% if signed_in? %>
                    <% if answer.votes.exists?(user_id: current_user.id) %>
                        <%= link_to '<i class="fa fa-sort-desc fa-3x"></i>'.html_safe, votes_answer_del_path(answer), method: :delete %>                    
                    <% else %>
                        <%= link_to '<i class="fa fa-sort-asc fa-3x"></i>'.html_safe, votes_answer_path(answer), method: :post %>
                    <% end %>
                    <%= answer.body %>
                    <% answer.comments.each do |comment| %>
                        <hr>
                        <%= markdown(comment.body) %>
                    <% end %>
                    
                    <%= form_for [answer,answer.comments.new] do |f| %>
                        <div class="comment">
                            <%=  f.text_area :body, class: "form-control input-lg", placeholder: "Comentar Respuesta" %>
                        </div>
                        <% if signed_in? %>
                            <div class="comment">
                                <%= f.submit "Comentar Respuesta", class: "btn btn-primary" %>
                                <%= f.hidden_field :user_id, :value => current_user.id%>
                            </div>  
                        <% end %>                 
                    <% end %>                 
                <% else %>
                    <%= link_to '<i class="fa fa-sort-asc fa-3x"></i>'.html_safe, new_user_session_path %>                    
                    <%= answer.body %>
                <% end %>                             
            <% end %>

            <% if signed_in? %>
                <br>
	            <h3>Tu Respuesta</h3>
                <% if @answer.errors.any? %>
                  <div class="alert alert-danger">
                    <ul>
                    <% @answer.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                <% end %>
                    </ul>
                  </div>
                <% end %>           

                <%= form_for [@question, @answer] do |f| %>
                    <div>
                        <%=  f.text_area :body, class: "form-control input-lg", placeholder: "Respuesta"  %>
                    </div>
                    <br>
                    <div>
                        <%= f.submit "Enviar Respuesta", class: "btn btn-primary" %>
                        <%= f.hidden_field :user_id, :value => current_user.id%>
                    </div>  
                <% end %> 
            <% end %>            
		</div><!--.col -->
	</div> <!--.row -->
</div> <!--.container -->