config/routes.rb
Rails.application.routes.draw do
  
  devise_for :views
  root 'questions#index'

  resources :questions do
    resources :comments, only: [:create]
    resources :answers, only: [:create]
    post 'votes', to: 'votes#create', as: 'votes'
    delete 'votes', to: 'votes#destroy', as: 'votes_del'
  end

  post 'votes/:answer_id', to: 'votes#create', as: 'votes_answer'  
  delete 'votes/:answer_id', to: 'votes#destroy', as: 'votes_answer_del'

  post 'comments/:answer_id', to: 'comments#create', as: 'answer_comments'  

  devise_for :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlowoverstackApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
    <!-- Header  -->
   <header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button><!-- .navbar-toggle -->          
            <%= link_to "Flowoverstack", root_path, class: "navbar-brand" %>          
        </div>

        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>                            
               <li><%= link_to 'Salir', destroy_user_session_path, method: :delete %></li>
            <% else %>
               <li><%= link_to "Ingresar", new_user_session_path %></li>
               <li><%= link_to "Registrarse", new_user_registration_path %></li>
            <% end %>   
            <li>
           <!-- Buscar Preguntas -->           
           <%= form_tag(questions_path, :method => "get", class: "navbar-form navbar-right", id: "search-form") do %>   
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar" %>
            <% end %>    
            </li>
          </ul>
        </div><!-- .collapse -->        
       </div> <!-- .container -->
    </nav>
  </header>
    <!-- End Header  -->    
    
  <% if flash[:notice] %>
    <div class="alert alert-info"> <%= flash[:notice] %> </div>
  <% end %>
  <div class="content">
    <% if signed_in? %>
      <center>Usuario: <strong><%= current_user.email %></strong></center>
    <% end %>        
    <%= yield %>
  </div>
  
</body>
</html>